@abstract
class_name SettingsTRKeys
extends RefCounted


const SETTINGS_TITLE: StringName = "UI.SETTINGS.TITLE"

const VOLUME_MASTER: StringName = "UI.SETTINGS.VOLUME.MASTER"
const VOLUME_MUSIC: StringName = "UI.SETTINGS.VOLUME.MUSIC"
const VOLUME_SFX: StringName = "UI.SETTINGS.VOLUME.SFX"

const CAMERA_SENSITIVITY: StringName = "UI.SETTINGS.CAMERA.MOUSE.SENSITIVITY"
const CAMERA_MOUSE_SENSITIVITY: StringName = "UI.SETTINGS.CAMERA.SENSITIVITY"

const SCREEN_RESOLUTION: StringName = "UI.SETTINGS.SCREEN.RESOLUTION"
const WINDOW_MODE: StringName = "UI.SETTINGS.WINDOW.MODE"
const WINDOW_MODE_WINDOWED: StringName = "UI.SETTINGS.WINDOW.MODE.WINDOWED"
const WINDOW_MODE_FULLSCREEN: StringName = "UI.SETTINGS.WINDOW.MODE.FULLSCREEN"
const WINDOW_MODE_BORDERLESS: StringName = "UI.SETTINGS.WINDOW.MODE.BORDERLESS"
const GRAPHIC_QUALITY: StringName = "UI.SETTINGS.GRAPHIC.QUALITY"

const LANGUAGE: StringName = "UI.SETTINGS.LANGUAGE"
const PORTUGUESE_BRAZIL: StringName = "UI.SETTINGS.LANGUAGE.PORTUGUESE_BRAZIL"
const JAPANESE: StringName = "UI.SETTINGS.LANGUAGE.JAPANESE"
const SPANISH_LATIN_AMERICA: StringName = "UI.SETTINGS.LANGUAGE.SPANISH_LATIN_AMERICA"
const ENGLISH_US: StringName = "UI.SETTINGS.LANGUAGE.ENGLISH_US"

const CUSTOMIZE_CONTROLS: StringName = "UI.SETTINGS.CUSTOMIZE.CONTROLS"
const BUTTON_CUSTOMIZE: StringName = "UI.SETTINGS.BUTTON.CUSTOMIZE"

const ERROR_SAVE_CONFIG: StringName = "ERROR.SAVE.CONFIG"
const ERROR_LOAD_CONFIG: StringName = "ERROR.LOAD.CONFIG"


func _dummy_extraact_keys() -> void:
	tr(SETTINGS_TITLE)

	tr(VOLUME_MASTER)
	tr(VOLUME_MUSIC)
	tr(VOLUME_SFX)

	tr(CAMERA_SENSITIVITY)
	tr(CAMERA_MOUSE_SENSITIVITY)

	tr(SCREEN_RESOLUTION)
	tr(WINDOW_MODE)
	tr(WINDOW_MODE_WINDOWED)
	tr(WINDOW_MODE_FULLSCREEN)
	tr(WINDOW_MODE_BORDERLESS)
	tr(GRAPHIC_QUALITY)

	tr(LANGUAGE)
	tr(PORTUGUESE_BRAZIL)
	tr(JAPANESE)
	tr(SPANISH_LATIN_AMERICA)
	tr(ENGLISH_US)

	tr(CUSTOMIZE_CONTROLS)
	tr(BUTTON_CUSTOMIZE)
	
	tr(ERROR_SAVE_CONFIG)
	tr(ERROR_LOAD_CONFIG)
